// src/staff_webapp/src/app/pages/login-page/login-page.component.ts
import { Component } from '@angular/core';
import { ReactiveFormsModule , FormGroup, FormControl } from '@angular/forms';
import { Router } from '@angular/router';
import { SessionService } from '../../services/session.service';
import { ApiKeyService } from '../../services/api-key.service';

@Component({
  selector: 'app-login-page',
  standalone: true,
  imports: [ReactiveFormsModule],
  templateUrl: './login-page.component.html',
})
export class LoginPageComponent {
  loginForm: FormGroup;

  constructor(
    private router: Router,
    private sessionService: SessionService,
    private apiKeyService: ApiKeyService
  ) {
    this.loginForm = new FormGroup({
      username: new FormControl(''),
      password: new FormControl(''),
    });
  }

  handleLogin() {
    console.log(this.loginForm.value);
    this.sessionService.postSession(this.loginForm.value).subscribe({
      next: (response: any) => {
        console.log(response)
        console.log(`Session key: ${response.data.sessionKey}`)
        this.apiKeyService.setSession(response.data.sessionKey)
        this.router.navigate(['/dashboard']);
      },
      error: (response: any) => {
        console.log(response);
        console.log(response.status);
        alert(`Login Failed: \n${response.error.message}`);
      }
    });
  }
}

<div class="flex justify-center items-center h-screen flex-col bg-primary">
	<h3 class="text-3xl mb-4 font-bold tracking-widest">Admin Dashboard</h3>
	<form [formGroup]="loginForm" (ngSubmit)="handleLogin()"
		class="border p-7 rounded-xl bg-white shadow-lg w-80 sm:w-96">
		<div class="flex justify-center mb-5">
			<img src="../../../assets/conciergevector.svg" alt="Concierge" class="h-30 object-contain" />
		</div>
		<div class="mb-3">
			<label htmlFor="room-num-input" class="block font-thin text-sm">Username</label>
			<input id="room-num-input" type="text" formControlName="username" placeholder="username"
				class="px-4 py-3 w-full rounded-lg border border-neutral-200" />
		</div>
		<div class="mb-3">
			<label htmlFor="pass-code-input" class="block font-thin text-sm">Password</label>
			<input id="pass-code-input" type="password" formControlName="password" placeholder="password"
				class="px-4 py-3 w-full rounded-lg border border-neutral-200" />
		</div>
		<div class="grid place-content-center mt-5">
			<button type="submit" [disabled]="loginForm.invalid" class="px-3 py-2 bg-black text-white rounded-lg">
				Sign In
				<i class="fas fa-sign-in-alt ml-1"></i>
			</button>
		</div>
	</form>
</div>

// src/guest_webapp/src/pages/LoginPage.jsx
import React, { useState } from "react";
import { setSessionKey } from "../utils/auth";
import conciergeVector from "../assets/conciergevector.svg";

const LoginPage = () => {
  const [roomKey, setRoomKey] = useState("");
  const [roomNum, setRoomNum] = useState("");
  const [error, setError] = useState(null);

  const handleSubmit = async (event) => {
    event.preventDefault();

    try {
      const response = await fetch(
        `${import.meta.env.VITE_API_BASE_URL}/sessions`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            username: `${roomNum}`,
            password: `${roomKey}`,
          }),
        }
      );
      if (!response.ok) {
        const errMsg = await response.json();
        setError(errMsg.error || errMsg.message || "Login Failed");
        return;
      }
      const data = await response.json();
      setSessionKey(data.data.sessionKey);
      sessionStorage.setItem("roomKey", roomKey);
      sessionStorage.setItem("roomNum", roomNum);
      window.location.href = "/home";
    } catch (error) {
      console.log(error);
      setError("Login Failed");
    }
  };

  return (
    <div className="flex bg-secondary items-center justify-center min-h-screen bg-gradient-to-r from-beige-200 to-beige-500 p-4">
      <div className="bg-lightPrimary p-6 sm:p-8 lg:p-10 rounded-lg shadow-xl max-w-md w-full">
        <h1 className="text-2xl sm:text-3xl font-semibold text-center text-black">
          Welcome to
        </h1>
        <div className="flex justify-center mb-5">
          <img
            src={conciergeVector}
            alt="Concierge"
            className="h-24 object-contain"
          />
        </div>
        <form onSubmit={handleSubmit}>
          <label
            htmlFor="roomNum"
            className="block text-sm font-medium text-gray-700 mb-2"
          >
            Enter Your Key Number:
          </label>
          <input
            type="text"
            id="roomNum"
            value={roomNum}
            onChange={(e) => setRoomNum(e.target.value)}
            className="block w-full p-2 sm:p-3 border border-gray-300 rounded-md mb-3 sm:mb-4 focus:ring-2 focus:ring-primary shadow-sm hover:shadow-md transition duration-200"
            placeholder="Room #"
          />
          
          <label
            htmlFor="roomKey"
            className="block text-sm font-medium text-gray-700 mb-2"
          >
            Enter Your Key Code:
          </label>
          <input
            type="text"
            id="roomKey"
            value={roomKey}
            onChange={(e) => setRoomKey(e.target.value)}
            className="block w-full p-2 sm:p-3 border border-gray-300 rounded-md mb-3 sm:mb-4 focus:ring-2 focus:ring-primary shadow-sm hover:shadow-md transition duration-200"
            placeholder="Key Code"
          />
          {error && <p className="text-red-500">Error: {error}</p>}
          <button
            type="submit"
            className="w-full bg-black text-white py-2 sm:py-3 rounded-md hover:bg-primary hover:text-black transition duration-200"
          >
            Login
          </button>
        </form>
      </div>
    </div>
  );
};

export default LoginPage;
